INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES ('Uladzimir', '1', 1);

INSERT INTO AUTHORITIES(ID, USERNAME, AUTHORITY)
VALUES (1, 'Uladzimir', 'read');
INSERT INTO AUTHORITIES(ID, USERNAME, AUTHORITY)
VALUES (2, 'Uladzimir', 'write');