CREATE TABLE USERS
(
    USERNAME VARCHAR(45) NOT NULL PRIMARY KEY,
    PASSWORD TEXT        NOT NULL,
    ENABLED  INT
);

CREATE TABLE AUTHORITIES
(
    ID        BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME  VARCHAR(45),
    AUTHORITY VARCHAR(45)
)