CREATE TABLE USER
(
    ID       BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL
);

CREATE TABLE OTP
(
    ID       BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    OTP      VARCHAR(45) NOT NULL
)